from transfer_loss_funcs.adv import *
from transfer_loss_funcs.bnm import *
from transfer_loss_funcs.coral import *
from transfer_loss_funcs.daan import *
from transfer_loss_funcs.lmmd import *
from transfer_loss_funcs.mmd import *
from transfer_loss_funcs.mmd_adv import *
from transfer_loss_funcs.plmmd import *
from transfer_loss_funcs.plmmd_adv import *
from transfer_loss_funcs.lmmd_adv import *
